### ISSUE TITLE
Crash without group parentheses,

### ISSUE THREAD

**Issue by phaag** [snake5/sgregex#3]
Hi,
I am just evaluating a small C regex library and found your project. Thanks for that project!

However, I have a problem, that the matching process crashes:
```
Assertion failed: (R->captures[ 0 ][1] != RX_NULL_OFFSET), function srx_MatchExt, file sgregex.c, line 1218.
' like 'GET|POST'+Abort
```

You can reproduce this, if you add the following line in sgregex_test.c in the MATCHTEST section:
```
MATCHTEST("GET /index.html HTTP/1.1\r\n", "GET|POST", 1);
```

If you add group parentheses, it works:
```
MATCHTEST("GET /index.html HTTP/1.1\r\n", "(GET|POST)", 1);
```

Although "GET|POST" is a valid regex, it crashes.

Thanks for your support.

**Comment by archo5** [comment]
Hi, thanks for the report!

Unfortunately the project is no longer being maintained as anything added since October 2014 may be "taken" by a bad employment contract (I tried to ask them to sort out the issue several times but unexpectedly it turns out the [person in charge](https://lv.linkedin.com/in/atisstraujums) is an a**hole - tried to use it as a bargaining chip for recruiting me back to the company - so realistically I don't think I have any chances of getting full rights back).

If the intended use case is such that anything related to ownership/licensing doesn't matter (internal prototype code or such), I can look into the issue, otherwise I'd recommend looking for a different library.

P.S. Sorry for wasting your time with the library, I should've put some kind of notice in the front page of all affected projects but neglected to do that as the interest surrounding random GitHub projects is generally low.

**Comment by phaag** [comment]
Well - that's bad new. The License file says, it's free and open, therefore I had a look at it. If I fork it under the current license terms and try to fix it myself I can certainly try that. I wanted to integrate integrate it into my nfdump open source project, which has a similar license term. 
Anyway thanks for responding and I will have a look myself at the issue.
